sudo: required
services:
  - docker

before_install:
  - docker build -t jossiemathews/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jossiemathews/react-test npm run test -- --coverage

after_success:
  - docker build -t jossiemathews/multi-client ./client
  - docker build -t jossiemathews/multi-nginx ./nginx
  - docker build -t jossiemathews/multi-server ./server
  - docker build -t jossiemathews/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push jossiemathews/multi-client
  - docker push jossiemathews/multi-nginx
  - docker push jossiemathews/multi-server
  - docker push jossiemathews/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-885750698421"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
